name: helpdesk-api-dev

services:
  api:
    profiles:
      - "api"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mydatabase

  postgres:
    extends:
      file: compose.yaml
      service: postgres
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - dev-pgdata:/var/lib/postgresql/data

volumes:
  dev-pgdata:
