spring.application.name=helpdesk

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Security / JWT
security.jwt.secret=${JWT_SECRET:helpdesk-local-dev-secret-helpdesk-local-dev-secret-123456}
security.jwt.expiration-ms=${JWT_EXPIRATION_MS:3600000}

# Actuator
management.endpoints.web.base-path=/actuator
management.endpoints.web.exposure.include=health,info,metrics,loggers
management.endpoint.health.show-details=when_authorized
management.info.env.enabled=true

# Logging
logging.level.root=INFO
logging.level.org.springframework.security=INFO
logging.level.com.thiagsilvadev.helpdesk=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%X{requestId:-}] [%thread] %logger{36} - %msg%n
