app.dev-admin.name=${DEV_ADMIN_NAME:Admin Dev}
app.dev-admin.email=${DEV_ADMIN_EMAIL:admin@helpdesk.local}
app.dev-admin.password=${DEV_ADMIN_PASSWORD:Admin@123456}
app.dev-user.name=${DEV_USER_NAME:Default User}
app.dev-user.email=${DEV_USER_EMAIL:user@helpdesk.local}
app.dev-user.password=${DEV_USER_PASSWORD:User@123456}
app.dev-tech.name=${DEV_TECH_NAME:Default Tech}
app.dev-tech.email=${DEV_TECH_EMAIL:tech@helpdesk.local}
app.dev-tech.password=${DEV_TECH_PASSWORD:Tech@123456}
