spring.application.name=helpdesk-api

# Load local .env file when present
spring.config.import=optional:file:.env[.properties]
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# Actuator
management.endpoints.web.base-path=/actuator
management.endpoints.web.exposure.include=health,info,metrics

# Logging
logging.pattern.correlation=[requestId:%X{requestId:-},traceId:%X{traceId:-},spanId:%X{spanId:-}]
